local set = vim.opt

set.relativenumber = true
set.number = true

set.cursorline = true
vim.opt.mouse = "a"            -- Enable mouse support
vim.opt.clipboard = "unnamedplus" -- Use system clipboard
vim.opt.swapfile = false       -- Disable swapfile
vim.opt.backup = false         -- Disable backup file
vim.opt.undofile = true        -- Enable persistent undo
vim.opt.autoread = true        -- Auto reload file changes
vim.opt.scrolloff = 8          -- Keep 8 lines visible when scrolling
vim.opt.sidescrolloff = 8      -- Keep 8 columns visible when scrolling sideways
vim.opt.expandtab = true       -- Convert tabs to spaces
vim.opt.shiftwidth = 3         -- Number of spaces per indentation level
vim.opt.tabstop = 3            -- Number of spaces per tab
vim.opt.softtabstop = 3        -- Spaces per tab in insert mode
vim.opt.smartindent = true     -- Smart indentation
vim.opt.autoindent = true      -- Copy indent from the previous line
vim.opt.hlsearch = false       -- Disable search highlight
vim.opt.incsearch = true       -- Highlight while typing search
vim.opt.ignorecase = true      -- Ignore case while searching
vim.opt.smartcase = true       -- Case-sensitive search when capital letter is used
vim.opt.termguicolors = true   -- Enable 24-bit colors
vim.opt.wrap = false           -- Disable line wrapping
vim.opt.splitbelow = true      -- New horizontal split opens below
vim.opt.splitright = true      -- New vertical split opens to the right
vim.opt.equalalways = false    -- Don't auto-resize splits
vim.opt.winminwidth = 10       -- Minimum window width
vim.opt.updatetime = 300       -- Faster update time (default: 4000ms)
vim.opt.timeoutlen = 500       -- Time to wait for a mapped sequence (in ms)
vim.opt.lazyredraw = true      -- Don't redraw while executing macros
vim.opt.redrawtime = 1000      -- Limit time for syntax highlighting
vim.opt.showmode = true        -- Hide mode (use statusline instead)
vim.opt.cmdheight = 1          -- More space in command line
vim.opt.laststatus = 2         -- Always show statusline
vim.g.mapleader = " "  -- Set leader key to Space
